import { Store, schema } from 'modelence/server';

// This defines the structure for a single generated question
const questionSchema = schema.object({
  questionText: schema.string(),
  category: schema.string(), // e.g., "Technical", "Behavioral", "Situational"
  rationale: schema.string(), // Why the AI generated this question
});

export const dbQuestionGenerations = new Store('questionGenerations', {
  // Schema for the entire generation session
  schema: {
    // We store the original inputs for reference
    resume: schema.string(),
    jobDescription: schema.string(),
    
    // An array of questions generated by the AI
    generatedQuestions: schema.array(questionSchema), 

    // Built-in Modelence type for user references
    userId: schema.userId(), 
    createdAt: schema.date(),
  },

  // Configure MongoDB indexes
  indexes: [
    { key: { userId: 1 } },
  ],
});